package ca.billy.integration;

import org.junit.Before;
import org.junit.Test;

import ca.billy.FileCompiler;
import ca.billy.Log;

/**
 * Only verify that the compiler don't fail but the generated bytecode is not checked.<BR>
 * TODO verify the generated bytecode
 */
public class IntegrationTest {

    private FileCompiler fileCompiler;

    @Before
    public void setup() {
        Log.enable();
        fileCompiler = new FileCompiler();     
    }

    @Test
    public void testHelloWorld() throws Exception {
        fileCompiler.compileFile("src/test/resources/integration/HelloWorld.billy");
        fileCompiler.writeByteCode();
    }

    @Test
    public void testHelloWorldWithStaticMethod() throws Exception {
        fileCompiler.compileFile("src/test/resources/integration/HelloWorldStatic.billy");
        fileCompiler.writeByteCode();
    }

    @Test
    public void testIf() throws Exception {
        fileCompiler.compileFile("src/test/resources/integration/If.billy");
        fileCompiler.writeByteCode();
    }

    @Test
    public void testVariableDef() {
        fileCompiler.compileFile("src/test/resources/integration/VariableDef.billy");
        fileCompiler.writeByteCode();
    }
    
    @Test
    public void testTicTacToe() {
        fileCompiler.compileFile("src/test/resources/integration/TicTacToe.billy");
        fileCompiler.writeByteCode();
    }

}
